### ISSUE TITLE
Multiple VPN version

### ISSUE THREAD

**Issue by mtompkins** [lynxthecat/cake-wg-pbr#3]
Thanks for sharing this script. 

I was curious if you might consider a version for multiple VPNs. I think many of us are finding a need to policy route traffic across different VPN endpoints and managing the bandwidth intelligently across is problematic. With the current version (as I understand it) we can only associate a single endpoint with `vpn_if=`

**Comment by lynxthecat** [comment]
For more complicated setups like this have you considered; 

https://github.com/lynxthecat/cake-dual-ifb

**Comment by mtompkins** [comment]
Thank you - I'll give it a look!
